// Base de datos de stikers por temática
const PRECIOS = {
  comun:  { '4x4': 111, '5x5': 150, '6x6': 190 },
  vinilo: { '4x4': 222, '5x5': 290, '6x6': 360 }
};

const catalogos = {

  urbano: {
    nombre: "Urbano",
    emoji: "🏙️",
    color: "urbano-bg",
    stikers: [
      { id: "u1",  nombre: "Graffiti tag",           emoji: "🎨" },
      { id: "u2",  nombre: "Skate urbano",           emoji: "🛹" },
      { id: "u3",  nombre: "Hip hop crew",           emoji: "🎤" },
      { id: "u4",  nombre: "Gorra NY",               emoji: "🧢" },
      { id: "u5",  nombre: "Zapatillas retro",       emoji: "👟" },
      { id: "u6",  nombre: "Auriculares callejeros", emoji: "🎧" },
      { id: "u7",  nombre: "Spray paint",            emoji: "🖌️" },
      { id: "u8",  nombre: "Cityscape noche",        emoji: "🌆" },
      { id: "u9",  nombre: "Breakdance move",        emoji: "💃" },
      { id: "u10", nombre: "BMX bici",               emoji: "🚲" },
      { id: "u11", nombre: "Cadenas de oro",         emoji: "📿" },
      { id: "u12", nombre: "Pared grafiteada",       emoji: "🧱" },
      { id: "u13", nombre: "Crew fist",              emoji: "✊" },
      { id: "u14", nombre: "Calle de noche",         emoji: "🌃" },
      { id: "u15", nombre: "Underground arte",       emoji: "🚇" },
    ]
  },

  argento: {
    nombre: "Argento",
    emoji: "🇦🇷",
    color: "argento-bg",
    stikers: [
      { id: "ar1",  nombre: "Mate",                  emoji: "🧉" },
      { id: "ar2",  nombre: "Asado parrilla",        emoji: "🥩" },
      { id: "ar3",  nombre: "Bandera Argentina",     emoji: "🇦🇷" },
      { id: "ar4",  nombre: "Alfajor",               emoji: "🍫" },
      { id: "ar5",  nombre: "Gaucho pampa",          emoji: "🤠" },
      { id: "ar6",  nombre: "Tango porteño",         emoji: "💃" },
      { id: "ar7",  nombre: "Empanada",              emoji: "🥟" },
      { id: "ar8",  nombre: "Yerba mate",            emoji: "🌿" },
      { id: "ar9",  nombre: "Buenos Aires",          emoji: "🏙️" },
      { id: "ar10", nombre: "Patagonia helada",      emoji: "🏔️" },
      { id: "ar11", nombre: "Vino Malbec",           emoji: "🍷" },
      { id: "ar12", nombre: "Facón cuchillo",        emoji: "🗡️" },
      { id: "ar13", nombre: "Poncho típico",         emoji: "🧣" },
      { id: "ar14", nombre: "Obelisco BA",           emoji: "🗼" },
      { id: "ar15", nombre: "Dulce de leche",        emoji: "🍮" },
    ]
  },

  turismo: {
    nombre: "Turismo",
    emoji: "✈️",
    color: "turismo-bg",
    stikers: [
      { id: "t1",  nombre: "Cataratas Iguazú",       emoji: "💧" },
      { id: "t2",  nombre: "Glaciar Perito Moreno",  emoji: "🧊" },
      { id: "t3",  nombre: "Obelisco porteño",       emoji: "🗼" },
      { id: "t4",  nombre: "Bariloche nieve",        emoji: "⛷️" },
      { id: "t5",  nombre: "Mendoza viñedos",        emoji: "🍇" },
      { id: "t6",  nombre: "Salta cerros",           emoji: "🏜️" },
      { id: "t7",  nombre: "Mar del Plata",          emoji: "🏖️" },
      { id: "t8",  nombre: "Ushuaia fin del mundo",  emoji: "🌍" },
      { id: "t9",  nombre: "Córdoba sierras",        emoji: "⛰️" },
      { id: "t10", nombre: "Avión viajero",          emoji: "✈️" },
      { id: "t11", nombre: "Mochilero aventura",     emoji: "🎒" },
      { id: "t12", nombre: "Pasaporte sello",        emoji: "🗺️" },
      { id: "t13", nombre: "Brújula viajera",        emoji: "🧭" },
      { id: "t14", nombre: "Palmera playa",          emoji: "🌴" },
      { id: "t15", nombre: "Camper van viajera",     emoji: "🚐" },
    ]
  },

  trap: {
    nombre: "Trap / Rap / Reggaeton",
    emoji: "🎤",
    color: "trap-bg",
    stikers: [
      { id: "tr1",  nombre: "Micrófono trap",        emoji: "🎤" },
      { id: "tr2",  nombre: "Cadenas de oro",        emoji: "⛓️" },
      { id: "tr3",  nombre: "Billetes rain",         emoji: "💸" },
      { id: "tr4",  nombre: "Gorra plana",           emoji: "🧢" },
      { id: "tr5",  nombre: "Grillz diamante",       emoji: "💎" },
      { id: "tr6",  nombre: "Champagne pop",         emoji: "🍾" },
      { id: "tr7",  nombre: "Spray grafiti",         emoji: "🎨" },
      { id: "tr8",  nombre: "Auriculares beats",     emoji: "🎧" },
      { id: "tr9",  nombre: "Anillos bling",         emoji: "💍" },
      { id: "tr10", nombre: "Star tattoo",           emoji: "⭐" },
      { id: "tr11", nombre: "Auto lujoso",           emoji: "🚗" },
      { id: "tr12", nombre: "Nota musical",          emoji: "🎵" },
      { id: "tr13", nombre: "Diamond hands",         emoji: "🙌" },
      { id: "tr14", nombre: "Stage lights",          emoji: "💡" },
      { id: "tr15", nombre: "Crown rap king",        emoji: "👑" },
    ]
  },

  musica: {
    nombre: "Música",
    emoji: "🎵",
    color: "musica-bg",
    stikers: [
      { id: "mu1",  nombre: "Guitarra eléctrica",    emoji: "🎸" },
      { id: "mu2",  nombre: "Piano de cola",         emoji: "🎹" },
      { id: "mu3",  nombre: "Batería rock",          emoji: "🥁" },
      { id: "mu4",  nombre: "Violín clásico",        emoji: "🎻" },
      { id: "mu5",  nombre: "Saxofón jazz",          emoji: "🎷" },
      { id: "mu6",  nombre: "Auriculares DJ",        emoji: "🎧" },
      { id: "mu7",  nombre: "Micrófono clásico",     emoji: "🎙️" },
      { id: "mu8",  nombre: "Nota musical",          emoji: "🎵" },
      { id: "mu9",  nombre: "Vinilo LP",             emoji: "💿" },
      { id: "mu10", nombre: "Trompeta jazz",         emoji: "🎺" },
      { id: "mu11", nombre: "Bajo eléctrico",        emoji: "🎸" },
      { id: "mu12", nombre: "Acordeón",              emoji: "🪗" },
      { id: "mu13", nombre: "Consola DJ",            emoji: "🎛️" },
      { id: "mu14", nombre: "Parlante boom",         emoji: "📢" },
      { id: "mu15", nombre: "Cassette retro",        emoji: "📼" },
    ]
  },

  420: {
    nombre: "420",
    emoji: "🍃",
    color: "cuatro21-bg",
    stikers: [
      { id: "420_1",  nombre: "Hoja verde",          emoji: "🍃" },
      { id: "420_2",  nombre: "Peace & love",        emoji: "☮️" },
      { id: "420_3",  nombre: "Arcoíris hippie",     emoji: "🌈" },
      { id: "420_4",  nombre: "Tie dye psicodélico", emoji: "🎨" },
      { id: "420_5",  nombre: "Van hippie",          emoji: "🚐" },
      { id: "420_6",  nombre: "Oso cósmico",         emoji: "🐻" },
      { id: "420_7",  nombre: "Hongo mágico",        emoji: "🍄" },
      { id: "420_8",  nombre: "Cristal brillante",   emoji: "💎" },
      { id: "420_9",  nombre: "Espiral cósmica",     emoji: "🌀" },
      { id: "420_10", nombre: "Estrellas mágicas",   emoji: "✨" },
      { id: "420_11", nombre: "Ojos relajados",      emoji: "😌" },
      { id: "420_12", nombre: "Luna mística",        emoji: "🌙" },
      { id: "420_13", nombre: "Cosmos profundo",     emoji: "🌌" },
      { id: "420_14", nombre: "Corazón verde",       emoji: "💚" },
      { id: "420_15", nombre: "Planeta Tierra",      emoji: "🌍" },
    ]
  },

  futbol: {
    nombre: "Fútbol",
    emoji: "⚽",
    color: "futbol-bg",
    stikers: [
      { id: "fo1",  nombre: "Messi La Pulga",        emoji: "⭐" },
      { id: "fo2",  nombre: "Pelota de fútbol",      emoji: "⚽" },
      { id: "fo3",  nombre: "Gol épico",             emoji: "🥅" },
      { id: "fo4",  nombre: "Copa del Mundo",        emoji: "🏆" },
      { id: "fo5",  nombre: "Camiseta Argentina",    emoji: "🇦🇷" },
      { id: "fo6",  nombre: "Di María asistencia",   emoji: "👟" },
      { id: "fo7",  nombre: "Maradona La Mano",      emoji: "✋" },
      { id: "fo8",  nombre: "Boca Juniors",          emoji: "💛" },
      { id: "fo9",  nombre: "River Plate",           emoji: "❤️" },
      { id: "fo10", nombre: "Árbitro silbato",       emoji: "🟨" },
      { id: "fo11", nombre: "Tribuna fan",           emoji: "📣" },
      { id: "fo12", nombre: "Botín crack",           emoji: "👟" },
      { id: "fo13", nombre: "Tarjeta roja",          emoji: "🟥" },
      { id: "fo14", nombre: "Festejo campeón",       emoji: "🎉" },
      { id: "fo15", nombre: "El Diego Maradona",     emoji: "🐐" },
    ]
  },

  deportes: {
    nombre: "Deportes",
    emoji: "🏅",
    color: "deportes-bg",
    stikers: [
      { id: "de1",  nombre: "Basketball slam",       emoji: "🏀" },
      { id: "de2",  nombre: "Tenis ace",             emoji: "🎾" },
      { id: "de3",  nombre: "Natación olímpica",     emoji: "🏊" },
      { id: "de4",  nombre: "Boxeo guantes",         emoji: "🥊" },
      { id: "de5",  nombre: "Skateboard trick",      emoji: "🛹" },
      { id: "de6",  nombre: "Surf ola perfecta",     emoji: "🏄" },
      { id: "de7",  nombre: "Ciclismo ruta",         emoji: "🚴" },
      { id: "de8",  nombre: "Running maratón",       emoji: "🏃" },
      { id: "de9",  nombre: "Vóley playa",           emoji: "🏐" },
      { id: "de10", nombre: "Rugby scrum",           emoji: "🏉" },
      { id: "de11", nombre: "Ski en nieve",          emoji: "⛷️" },
      { id: "de12", nombre: "Medalla de oro",        emoji: "🥇" },
      { id: "de13", nombre: "Escalada",              emoji: "🧗" },
      { id: "de14", nombre: "Arco y flecha",         emoji: "🏹" },
      { id: "de15", nombre: "Halterofilia",          emoji: "🏋️" },
    ]
  },

  memes: {
    nombre: "Memes",
    emoji: "😂",
    color: "memes-bg",
    stikers: [
      { id: "me1",  nombre: "Pepe Frog",             emoji: "🐸" },
      { id: "me2",  nombre: "Doge wow",              emoji: "🐕" },
      { id: "me3",  nombre: "This is fine",          emoji: "🔥" },
      { id: "me4",  nombre: "Drake aprueba",         emoji: "👍" },
      { id: "me5",  nombre: "Woman yelling cat",     emoji: "😾" },
      { id: "me6",  nombre: "Distracted boyfriend",  emoji: "😏" },
      { id: "me7",  nombre: "Surprised Pikachu",     emoji: "😮" },
      { id: "me8",  nombre: "Crying laughing",       emoji: "😂" },
      { id: "me9",  nombre: "OK Boomer",             emoji: "👴" },
      { id: "me10", nombre: "Sus impostor",          emoji: "🔴" },
      { id: "me11", nombre: "Big brain",             emoji: "🧠" },
      { id: "me12", nombre: "Coffin dance",          emoji: "💃" },
      { id: "me13", nombre: "GigaChad",              emoji: "💪" },
      { id: "me14", nombre: "Stonks sube",           emoji: "📈" },
      { id: "me15", nombre: "Chad vs Virgin",        emoji: "😎" },
    ]
  },

  frases: {
    nombre: "Frases",
    emoji: "💬",
    color: "frases-bg",
    stikers: [
      { id: "fr1",  nombre: "Carpe Diem",            emoji: "☀️" },
      { id: "fr2",  nombre: "No hay mal que dure",   emoji: "💪" },
      { id: "fr3",  nombre: "Vamos vamos",           emoji: "🔥" },
      { id: "fr4",  nombre: "Todo pasa",             emoji: "🌊" },
      { id: "fr5",  nombre: "La vida es bella",      emoji: "🌹" },
      { id: "fr6",  nombre: "Be happy",              emoji: "😊" },
      { id: "fr7",  nombre: "Dream big",             emoji: "💭" },
      { id: "fr8",  nombre: "Stay wild",             emoji: "🐺" },
      { id: "fr9",  nombre: "Good vibes only",       emoji: "✌️" },
      { id: "fr10", nombre: "No pain no gain",       emoji: "⚡" },
      { id: "fr11", nombre: "Believe",               emoji: "⭐" },
      { id: "fr12", nombre: "You got this",          emoji: "🙌" },
      { id: "fr13", nombre: "Hakuna Matata",         emoji: "🦁" },
      { id: "fr14", nombre: "Just do it",            emoji: "✔️" },
      { id: "fr15", nombre: "Live laugh love",       emoji: "💕" },
    ]
  },

  mascotas: {
    nombre: "Mascotas",
    emoji: "🐾",
    color: "mascotas-bg",
    stikers: [
      { id: "pa1",  nombre: "Perrito feliz",         emoji: "🐶" },
      { id: "pa2",  nombre: "Gatito curioso",        emoji: "🐱" },
      { id: "pa3",  nombre: "Conejito tierno",       emoji: "🐰" },
      { id: "pa4",  nombre: "Hamster rueda",         emoji: "🐹" },
      { id: "pa5",  nombre: "Pez dorado",            emoji: "🐟" },
      { id: "pa6",  nombre: "Tortuga mascota",       emoji: "🐢" },
      { id: "pa7",  nombre: "Loro parlanchín",       emoji: "🦜" },
      { id: "pa8",  nombre: "Golden retriever",      emoji: "🦮" },
      { id: "pa9",  nombre: "Gato persa",            emoji: "😺" },
      { id: "pa10", nombre: "Huella de pata",        emoji: "🐾" },
      { id: "pa11", nombre: "Cocker spaniel",        emoji: "🐕" },
      { id: "pa12", nombre: "Husky siberiano",       emoji: "🐺" },
      { id: "pa13", nombre: "Gato negro",            emoji: "🐈‍⬛" },
      { id: "pa14", nombre: "Periquito colorido",    emoji: "🦚" },
      { id: "pa15", nombre: "Lagartija",             emoji: "🦎" },
    ]
  },

  varios: {
    nombre: "Varios",
    emoji: "🌟",
    color: "varios-bg",
    stikers: [
      { id: "va1",  nombre: "Corazón arcoíris",      emoji: "🌈" },
      { id: "va2",  nombre: "Estrella brillante",    emoji: "⭐" },
      { id: "va3",  nombre: "Rayo power",            emoji: "⚡" },
      { id: "va4",  nombre: "Luna creciente",        emoji: "🌙" },
      { id: "va5",  nombre: "Sol radiante",          emoji: "☀️" },
      { id: "va6",  nombre: "Corona dorada",         emoji: "👑" },
      { id: "va7",  nombre: "Fuego ardiente",        emoji: "🔥" },
      { id: "va8",  nombre: "Diamante brillante",    emoji: "💎" },
      { id: "va9",  nombre: "Paz mundial",           emoji: "☮️" },
      { id: "va10", nombre: "Infinito",              emoji: "♾️" },
      { id: "va11", nombre: "Yin yang",              emoji: "☯️" },
      { id: "va12", nombre: "Trébol de la suerte",   emoji: "🍀" },
      { id: "va13", nombre: "Mariposa libre",        emoji: "🦋" },
      { id: "va14", nombre: "Globo de colores",      emoji: "🎈" },
      { id: "va15", nombre: "Nube con lluvia",       emoji: "🌧️" },
    ]
  },

  simpsons: {
    nombre: "Simpson",
    emoji: "🍩",
    color: "simpsons-bg",
    stikers: [
      { id: "s1",  nombre: "Homer durmiendo",        emoji: "😴" },
      { id: "s2",  nombre: "Bart con patineta",      emoji: "🛹" },
      { id: "s3",  nombre: "Lisa con saxo",          emoji: "🎷" },
      { id: "s4",  nombre: "Marge con escoba",       emoji: "🧹" },
      { id: "s5",  nombre: "Maggie con chupete",     emoji: "🍼" },
      { id: "s6",  nombre: "Homer y la dona",        emoji: "🍩" },
      { id: "s7",  nombre: "Bart en el pizarrón",    emoji: "📋" },
      { id: "s8",  nombre: "Homer gritando",         emoji: "😱" },
      { id: "s9",  nombre: "Ned Flanders",           emoji: "🙏" },
      { id: "s10", nombre: "Krusty el Payaso",       emoji: "🤡" },
      { id: "s11", nombre: "El Abuelo Abe",          emoji: "👴" },
      { id: "s12", nombre: "Milhouse",               emoji: "🤓" },
      { id: "s13", nombre: "Nelson Muntz",           emoji: "😝" },
      { id: "s14", nombre: "Burns y Smithers",       emoji: "💼" },
      { id: "s15", nombre: "Homer estrangula Bart",  emoji: "😤" },
      { id: "s16", nombre: "Bart al teléfono",       emoji: "📞" },
      { id: "s17", nombre: "Lisa estudiando",        emoji: "📚" },
      { id: "s18", nombre: "Homer con cerveza",      emoji: "🍺" },
      { id: "s19", nombre: "Marge sorprendida",      emoji: "😮" },
      { id: "s20", nombre: "Santa Claus Helper",     emoji: "🐕" },
      { id: "s21", nombre: "Snowball el gato",       emoji: "🐱" },
      { id: "s22", nombre: "Homer en el sofá",       emoji: "🛋️" },
      { id: "s23", nombre: "Bart skateboard grind",  emoji: "🤘" },
      { id: "s24", nombre: "Principal Skinner",      emoji: "😠" },
      { id: "s25", nombre: "Barney con cerveza",     emoji: "🍻" },
      { id: "s26", nombre: "Sideshow Bob",           emoji: "🔪" },
      { id: "s27", nombre: "Springfield sign",       emoji: "🌆" },
      { id: "s28", nombre: "Homer en el reactor",    emoji: "☢️" },
      { id: "s29", nombre: "Bart con honda",         emoji: "🏹" },
      { id: "s30", nombre: "La familia Simpson",     emoji: "👨‍👩‍👧‍👦" },
    ]
  },

  cine: {
    nombre: "Cine",
    emoji: "🎬",
    color: "cine-bg",
    stikers: [
      { id: "c1",  nombre: "Star Wars sable",        emoji: "⚔️" },
      { id: "c2",  nombre: "Darth Vader casco",      emoji: "🪖" },
      { id: "c3",  nombre: "Yoda sabio",             emoji: "🌿" },
      { id: "c4",  nombre: "E.T. extraterrestre",    emoji: "👽" },
      { id: "c5",  nombre: "Jaws el tiburón",        emoji: "🦈" },
      { id: "c6",  nombre: "Indiana Jones",          emoji: "🎩" },
      { id: "c7",  nombre: "Terminator",             emoji: "🤖" },
      { id: "c8",  nombre: "Pulp Fiction",           emoji: "🔫" },
      { id: "c9",  nombre: "El Padrino",             emoji: "🌹" },
      { id: "c10", nombre: "Jurassic Park",          emoji: "🦕" },
      { id: "c11", nombre: "Matrix pastilla roja",   emoji: "💊" },
      { id: "c12", nombre: "Forrest Gump caja",      emoji: "🍫" },
      { id: "c13", nombre: "Home Alone cara",        emoji: "😱" },
      { id: "c14", nombre: "Titanic corazón",        emoji: "💎" },
      { id: "c15", nombre: "Ghostbusters logo",      emoji: "👻" },
      { id: "c16", nombre: "Shining hacha",          emoji: "🪓" },
      { id: "c17", nombre: "Alien criatura",         emoji: "🐛" },
      { id: "c18", nombre: "Fight Club jabón",       emoji: "🧼" },
      { id: "c19", nombre: "Toy Story Buzz",         emoji: "🚀" },
      { id: "c20", nombre: "Toy Story Woody",        emoji: "🤠" },
      { id: "c21", nombre: "Lion King Simba",        emoji: "🦁" },
      { id: "c22", nombre: "Back to the Future",     emoji: "🚗" },
      { id: "c23", nombre: "Harry Potter varita",    emoji: "🪄" },
      { id: "c24", nombre: "Lord of the Rings",      emoji: "💍" },
      { id: "c25", nombre: "Rocky Balboa",           emoji: "🥊" },
      { id: "c26", nombre: "Top Gun avión",          emoji: "✈️" },
      { id: "c27", nombre: "Scarface Tony Montana",  emoji: "💰" },
      { id: "c28", nombre: "Beetlejuice",            emoji: "🐛" },
      { id: "c29", nombre: "Batman logo clásico",    emoji: "🦇" },
      { id: "c30", nombre: "Claqueta de cine",       emoji: "🎬" },
    ]
  },

  series: {
    nombre: "Series",
    emoji: "📺",
    color: "series-bg",
    stikers: [
      { id: "se1",  nombre: "Breaking Bad",          emoji: "⚗️" },
      { id: "se2",  nombre: "Game of Thrones",       emoji: "🐉" },
      { id: "se3",  nombre: "Friends Central Perk",  emoji: "☕" },
      { id: "se4",  nombre: "Stranger Things",       emoji: "🔦" },
      { id: "se5",  nombre: "The Office Dunder",     emoji: "📎" },
      { id: "se6",  nombre: "Black Mirror pantalla", emoji: "📱" },
      { id: "se7",  nombre: "Narcos Colombia",       emoji: "🌿" },
      { id: "se8",  nombre: "The Mandalorian",       emoji: "🪖" },
      { id: "se9",  nombre: "Peaky Blinders",        emoji: "🎩" },
      { id: "se10", nombre: "Dark reloj",            emoji: "🕰️" },
      { id: "se11", nombre: "La Casa de Papel",      emoji: "🔴" },
      { id: "se12", nombre: "Sherlock Holmes",       emoji: "🔍" },
      { id: "se13", nombre: "Chernobyl reactor",     emoji: "☢️" },
      { id: "se14", nombre: "The Last of Us",        emoji: "🍄" },
      { id: "se15", nombre: "Wednesday Addams",      emoji: "🖤" },
    ]
  },

  gamer: {
    nombre: "Gamer",
    emoji: "🎮",
    color: "games-bg",
    stikers: [
      { id: "v1",  nombre: "Mario Bros estrella",    emoji: "⭐" },
      { id: "v2",  nombre: "Luigi fantasma",         emoji: "👻" },
      { id: "v3",  nombre: "Princess Peach corona",  emoji: "👑" },
      { id: "v4",  nombre: "Bowser fuego",           emoji: "🔥" },
      { id: "v5",  nombre: "Link espada Zelda",      emoji: "🗡️" },
      { id: "v6",  nombre: "Triforce Zelda",         emoji: "🔺" },
      { id: "v7",  nombre: "Pac-Man comiendo",       emoji: "🟡" },
      { id: "v8",  nombre: "Space Invader clásico",  emoji: "👾" },
      { id: "v9",  nombre: "Sonic velocidad",        emoji: "💨" },
      { id: "v10", nombre: "Tails volando",          emoji: "✈️" },
      { id: "v11", nombre: "Master Chief casco",     emoji: "⚔️" },
      { id: "v12", nombre: "Kratos hachas",          emoji: "🪓" },
      { id: "v13", nombre: "Geralt de Rivia",        emoji: "⚡" },
      { id: "v14", nombre: "Minecraft Creeper",      emoji: "💚" },
      { id: "v15", nombre: "Minecraft diamante",     emoji: "💎" },
      { id: "v16", nombre: "Among Us impostor",      emoji: "🔴" },
      { id: "v17", nombre: "Fortnite llama",         emoji: "🦙" },
      { id: "v18", nombre: "Pokeball atrapa",        emoji: "🔵" },
      { id: "v19", nombre: "Pikachu 8-bit",          emoji: "⚡" },
      { id: "v20", nombre: "Street Fighter puño",    emoji: "👊" },
      { id: "v21", nombre: "Mortal Kombat logo",     emoji: "🐉" },
      { id: "v22", nombre: "Doom Slayer casco",      emoji: "💀" },
      { id: "v23", nombre: "Tetris bloques",         emoji: "🟦" },
      { id: "v24", nombre: "Control de PS5",         emoji: "🎮" },
      { id: "v25", nombre: "Control Xbox",           emoji: "🎮" },
      { id: "v26", nombre: "Nintendo Switch",        emoji: "🕹️" },
      { id: "v27", nombre: "Bomberman clásico",      emoji: "💣" },
      { id: "v28", nombre: "Donkey Kong barril",     emoji: "🐒" },
      { id: "v29", nombre: "Yoshi huevo",            emoji: "🥚" },
      { id: "v30", nombre: "Kirby aspirando",        emoji: "🌸" },
    ]
  },

  anime: {
    nombre: "Anime",
    emoji: "⚡",
    color: "anime-bg",
    stikers: [
      { id: "a1",  nombre: "Pikachu feliz",          emoji: "⚡" },
      { id: "a2",  nombre: "Goku Kame Hame",         emoji: "💥" },
      { id: "a3",  nombre: "Naruto Rasengan",        emoji: "🌀" },
      { id: "a4",  nombre: "Totoro durmiendo",       emoji: "🐻" },
      { id: "a5",  nombre: "No Face",                emoji: "👺" },
      { id: "a6",  nombre: "Luffy sombrero",         emoji: "🎩" },
      { id: "a7",  nombre: "Sailor Moon",            emoji: "🌙" },
      { id: "a8",  nombre: "Evangelion Unit 01",     emoji: "🤖" },
      { id: "a9",  nombre: "Dragon Ball esfera",     emoji: "⭐" },
      { id: "a10", nombre: "Vegeta orgullo",         emoji: "👑" },
      { id: "a11", nombre: "Itachi Uchiha",          emoji: "🔴" },
      { id: "a12", nombre: "Kakashi sensei",         emoji: "📖" },
      { id: "a13", nombre: "Zoro tres espadas",      emoji: "⚔️" },
      { id: "a14", nombre: "Nami mapa",              emoji: "🗺️" },
      { id: "a15", nombre: "Tanjiro espada",         emoji: "🌊" },
      { id: "a16", nombre: "Nezuko caja",            emoji: "📦" },
      { id: "a17", nombre: "Light Yagami notebook",  emoji: "📓" },
      { id: "a18", nombre: "Ryuk manzana",           emoji: "🍎" },
      { id: "a19", nombre: "Levi Ackerman",          emoji: "🗡️" },
      { id: "a20", nombre: "Eren Jaeger",            emoji: "🔑" },
      { id: "a21", nombre: "Mikasa pañuelo",         emoji: "🧣" },
      { id: "a22", nombre: "Hinata voleibol",        emoji: "🏐" },
      { id: "a23", nombre: "Gojo ojos",              emoji: "👁️" },
      { id: "a24", nombre: "Sukuna tatuajes",        emoji: "👹" },
      { id: "a25", nombre: "Deku Plus Ultra",        emoji: "💪" },
      { id: "a26", nombre: "All Might forma",        emoji: "🌟" },
      { id: "a27", nombre: "Kenshin espada",         emoji: "⚔️" },
      { id: "a28", nombre: "Inuyasha oídos",         emoji: "🐺" },
      { id: "a29", nombre: "Doraemon bolsillo",      emoji: "🔵" },
      { id: "a30", nombre: "Astro Boy cohete",       emoji: "🚀" },
    ]
  },

  girlspower: {
    nombre: "Girls Power",
    emoji: "💪",
    color: "girlspower-bg",
    stikers: [
      { id: "gp1",  nombre: "Feminismo fist",        emoji: "✊" },
      { id: "gp2",  nombre: "Labial rojo",           emoji: "💋" },
      { id: "gp3",  nombre: "Girl power corazón",    emoji: "💜" },
      { id: "gp4",  nombre: "Flores boho",           emoji: "🌸" },
      { id: "gp5",  nombre: "Mariposa free",         emoji: "🦋" },
      { id: "gp6",  nombre: "Estrellas brillantes",  emoji: "✨" },
      { id: "gp7",  nombre: "Unicornio mágico",      emoji: "🦄" },
      { id: "gp8",  nombre: "Diamante chica",        emoji: "💎" },
      { id: "gp9",  nombre: "Tacos altos",           emoji: "👠" },
      { id: "gp10", nombre: "Espejo mágico",         emoji: "🪞" },
      { id: "gp11", nombre: "Princesa guerrera",     emoji: "👸" },
      { id: "gp12", nombre: "Corazón feminista",     emoji: "💗" },
      { id: "gp13", nombre: "Luna mujer",            emoji: "🌙" },
      { id: "gp14", nombre: "Rosa salvaje",          emoji: "🌹" },
      { id: "gp15", nombre: "Boss chica",            emoji: "👩‍💼" },
    ]
  },

  infantilnene: {
    nombre: "Infantil Nene",
    emoji: "🚀",
    color: "infantilnene-bg",
    stikers: [
      { id: "in1",  nombre: "Dinosaurio rugiente",   emoji: "🦕" },
      { id: "in2",  nombre: "Auto de carreras",      emoji: "🏎️" },
      { id: "in3",  nombre: "Tren a vapor",          emoji: "🚂" },
      { id: "in4",  nombre: "Cohete espacial",       emoji: "🚀" },
      { id: "in5",  nombre: "Pirata aventurero",     emoji: "🏴‍☠️" },
      { id: "in6",  nombre: "Robot amigable",        emoji: "🤖" },
      { id: "in7",  nombre: "Tiburón divertido",     emoji: "🦈" },
      { id: "in8",  nombre: "Dragón amigo",          emoji: "🐉" },
      { id: "in9",  nombre: "Monster truck",         emoji: "🚛" },
      { id: "in10", nombre: "Superhéroe nene",       emoji: "🦸‍♂️" },
      { id: "in11", nombre: "Fútbol gol",            emoji: "⚽" },
      { id: "in12", nombre: "Astronauta niño",       emoji: "👨‍🚀" },
      { id: "in13", nombre: "Oso polar",             emoji: "🐻‍❄️" },
      { id: "in14", nombre: "Leon amigable",         emoji: "🦁" },
      { id: "in15", nombre: "Pulpo gracioso",        emoji: "🐙" },
    ]
  },

  infantilnena: {
    nombre: "Infantil Nena",
    emoji: "🦄",
    color: "infantilnena-bg",
    stikers: [
      { id: "ia1",  nombre: "Unicornio arcoíris",    emoji: "🦄" },
      { id: "ia2",  nombre: "Sirena del mar",        emoji: "🧜‍♀️" },
      { id: "ia3",  nombre: "Princesa castillo",     emoji: "👸" },
      { id: "ia4",  nombre: "Hada del bosque",       emoji: "🧚‍♀️" },
      { id: "ia5",  nombre: "Mariposa brillante",    emoji: "🦋" },
      { id: "ia6",  nombre: "Arcoíris pastel",       emoji: "🌈" },
      { id: "ia7",  nombre: "Flor mágica",           emoji: "🌺" },
      { id: "ia8",  nombre: "Corona de princesa",    emoji: "👑" },
      { id: "ia9",  nombre: "Gato con lazo",         emoji: "🎀" },
      { id: "ia10", nombre: "Cupcake decorado",      emoji: "🧁" },
      { id: "ia11", nombre: "Hada madrina",          emoji: "🪄" },
      { id: "ia12", nombre: "Estrella fugaz",        emoji: "🌟" },
      { id: "ia13", nombre: "Nube con corazón",      emoji: "💕" },
      { id: "ia14", nombre: "Globos de colores",     emoji: "🎈" },
      { id: "ia15", nombre: "Gatito tierno",         emoji: "🐱" },
    ]
  },

  superheroes: {
    nombre: "Super Heroes",
    emoji: "🦸",
    color: "heroes-bg",
    stikers: [
      { id: "h1",  nombre: "Superman logo S",        emoji: "🔵" },
      { id: "h2",  nombre: "Batman señal",           emoji: "🦇" },
      { id: "h3",  nombre: "Spider-Man telaraña",    emoji: "🕷️" },
      { id: "h4",  nombre: "Iron Man casco",         emoji: "🔴" },
      { id: "h5",  nombre: "Captain America escudo", emoji: "🛡️" },
      { id: "h6",  nombre: "Thor martillo",          emoji: "🔨" },
      { id: "h7",  nombre: "Hulk fuerza",            emoji: "💪" },
      { id: "h8",  nombre: "Black Widow logo",       emoji: "⏳" },
      { id: "h9",  nombre: "Hawkeye flecha",         emoji: "🏹" },
      { id: "h10", nombre: "Wolverine garras",       emoji: "✊" },
      { id: "h11", nombre: "Deadpool mascara",       emoji: "😈" },
      { id: "h12", nombre: "Doctor Strange ojo",     emoji: "👁️" },
      { id: "h13", nombre: "Black Panther garra",    emoji: "🐆" },
      { id: "h14", nombre: "Wonder Woman tiara",     emoji: "⭐" },
      { id: "h15", nombre: "Flash rayo",             emoji: "⚡" },
      { id: "h16", nombre: "Green Lantern anillo",   emoji: "💚" },
      { id: "h17", nombre: "Aquaman tridente",       emoji: "🔱" },
      { id: "h18", nombre: "Cyborg circuitos",       emoji: "🤖" },
      { id: "h19", nombre: "Shazam rayo",            emoji: "⚡" },
      { id: "h20", nombre: "Ant-Man micro",          emoji: "🐜" },
      { id: "h21", nombre: "Vision frente",          emoji: "💜" },
      { id: "h22", nombre: "Scarlet Witch corona",   emoji: "🔮" },
      { id: "h23", nombre: "Thanos guante",          emoji: "✊" },
      { id: "h24", nombre: "Loki casco",             emoji: "🐍" },
      { id: "h25", nombre: "Joker carta",            emoji: "🃏" },
      { id: "h26", nombre: "Penguins paraguas",      emoji: "☂️" },
      { id: "h27", nombre: "The Flash velocidad",    emoji: "💨" },
      { id: "h28", nombre: "Green Arrow arco",       emoji: "🏹" },
      { id: "h29", nombre: "Venom simbiot",          emoji: "🖤" },
      { id: "h30", nombre: "Avengers logo A",        emoji: "🦸" },
    ]
  },

  naturaleza: {
    nombre: "Naturaleza",
    emoji: "🌿",
    color: "nat-bg",
    stikers: [
      { id: "n1",  nombre: "Rosa roja",              emoji: "🌹" },
      { id: "n2",  nombre: "Girasol brillante",      emoji: "🌻" },
      { id: "n3",  nombre: "Hoja tropical",          emoji: "🌿" },
      { id: "n4",  nombre: "Cactus lindo",           emoji: "🌵" },
      { id: "n5",  nombre: "Árbol de cerezo",        emoji: "🌸" },
      { id: "n6",  nombre: "Mariposa azul",          emoji: "🦋" },
      { id: "n7",  nombre: "Abeja melífera",         emoji: "🐝" },
      { id: "n8",  nombre: "Tortuga marina",         emoji: "🐢" },
      { id: "n9",  nombre: "Zorro astuto",           emoji: "🦊" },
      { id: "n10", nombre: "Koala dormido",          emoji: "🐨" },
      { id: "n11", nombre: "Panda comiendo",         emoji: "🐼" },
      { id: "n12", nombre: "Lobo luna llena",        emoji: "🐺" },
      { id: "n13", nombre: "Búho nocturno",          emoji: "🦉" },
      { id: "n14", nombre: "Flamenco rosa",          emoji: "🦩" },
      { id: "n15", nombre: "Loro tropical",          emoji: "🦜" },
      { id: "n16", nombre: "Rana de colores",        emoji: "🐸" },
      { id: "n17", nombre: "Elefante sabio",         emoji: "🐘" },
      { id: "n18", nombre: "León rey",               emoji: "🦁" },
      { id: "n19", nombre: "Tigre poderoso",         emoji: "🐯" },
      { id: "n20", nombre: "Ballena azul",           emoji: "🐋" },
      { id: "n21", nombre: "Delfín saltando",        emoji: "🐬" },
      { id: "n22", nombre: "Pulpo inteligente",      emoji: "🐙" },
      { id: "n23", nombre: "Montaña nevada",         emoji: "🏔️" },
      { id: "n24", nombre: "Cascada tropical",       emoji: "💧" },
      { id: "n25", nombre: "Luna y estrellas",       emoji: "🌙" },
      { id: "n26", nombre: "Arcoíris brillante",     emoji: "🌈" },
      { id: "n27", nombre: "Sol radiante",           emoji: "☀️" },
      { id: "n28", nombre: "Ola del mar",            emoji: "🌊" },
      { id: "n29", nombre: "Volcán activo",          emoji: "🌋" },
      { id: "n30", nombre: "Árbol del mundo",        emoji: "🌳" },
    ]
  },

  halloween: {
    nombre: "Halloween / Terror",
    emoji: "🎃",
    color: "halloween-bg",
    stikers: [
      { id: "hw1",  nombre: "Calabaza Jack",         emoji: "🎃" },
      { id: "hw2",  nombre: "Calavera",              emoji: "💀" },
      { id: "hw3",  nombre: "Fantasma",              emoji: "👻" },
      { id: "hw4",  nombre: "Murciélago nocturno",   emoji: "🦇" },
      { id: "hw5",  nombre: "Telaraña",              emoji: "🕸️" },
      { id: "hw6",  nombre: "Araña terrorífica",     emoji: "🕷️" },
      { id: "hw7",  nombre: "Sombrero de bruja",     emoji: "🧙‍♀️" },
      { id: "hw8",  nombre: "Zombie",                emoji: "🧟" },
      { id: "hw9",  nombre: "Hombre lobo",           emoji: "🐺" },
      { id: "hw10", nombre: "Drácula",               emoji: "🧛" },
      { id: "hw11", nombre: "Gato negro",            emoji: "🐈‍⬛" },
      { id: "hw12", nombre: "Caldero mágico",        emoji: "🪄" },
      { id: "hw13", nombre: "Ojo malvado",           emoji: "👁️" },
      { id: "hw14", nombre: "Demonio",               emoji: "👹" },
      { id: "hw15", nombre: "RIP lápida",            emoji: "🪦" },
    ]
  },

  cosmo: {
    nombre: "Cosmo / Religión",
    emoji: "🔮",
    color: "cosmo-bg",
    stikers: [
      { id: "co1",  nombre: "Om símbolo",            emoji: "🕉️" },
      { id: "co2",  nombre: "Fases de la luna",      emoji: "🌙" },
      { id: "co3",  nombre: "Mandala sagrado",       emoji: "🌀" },
      { id: "co4",  nombre: "Yin yang equilibrio",   emoji: "☯️" },
      { id: "co5",  nombre: "Ojo de Horus",          emoji: "👁️" },
      { id: "co6",  nombre: "Loto sagrado",          emoji: "🪷" },
      { id: "co7",  nombre: "Cristal de cuarzo",     emoji: "💎" },
      { id: "co8",  nombre: "Zodíaco astral",        emoji: "♈" },
      { id: "co9",  nombre: "Sol cósmico",           emoji: "☀️" },
      { id: "co10", nombre: "Ángel guardián",        emoji: "😇" },
      { id: "co11", nombre: "Universo infinito",     emoji: "🌌" },
      { id: "co12", nombre: "Estrella de David",     emoji: "✡️" },
      { id: "co13", nombre: "Cruz sagrada",          emoji: "✝️" },
      { id: "co14", nombre: "Media luna islámica",   emoji: "☪️" },
      { id: "co15", nombre: "Pirámide de energía",   emoji: "🔺" },
    ]
  },

  monocromaticos: {
    nombre: "Monocromáticos",
    emoji: "🖤",
    color: "mono-bg",
    stikers: [
      { id: "mo1",  nombre: "Corazón negro",         emoji: "🖤" },
      { id: "mo2",  nombre: "Estrella blanca",       emoji: "⭐" },
      { id: "mo3",  nombre: "Luna dark",             emoji: "🌑" },
      { id: "mo4",  nombre: "Flecha minimalista",    emoji: "➡️" },
      { id: "mo5",  nombre: "Triángulo geométrico",  emoji: "🔺" },
      { id: "mo6",  nombre: "Círculo simple",        emoji: "⭕" },
      { id: "mo7",  nombre: "Rosa línea art",        emoji: "🌹" },
      { id: "mo8",  nombre: "Cara abstracta",        emoji: "🎭" },
      { id: "mo9",  nombre: "Lobo silueta",          emoji: "🐺" },
      { id: "mo10", nombre: "Pájaro silueta",        emoji: "🐦" },
      { id: "mo11", nombre: "Gato minimalista",      emoji: "🐱" },
      { id: "mo12", nombre: "Rayo geométrico",       emoji: "⚡" },
      { id: "mo13", nombre: "Infinito dark",         emoji: "♾️" },
      { id: "mo14", nombre: "Cruz minimalista",      emoji: "✚" },
      { id: "mo15", nombre: "Huella dactilar",       emoji: "🖐️" },
    ]
  }

};
